"""Technology signature tables.

Everything here is a lookup table, deliberately: the deterministic layer must
be auditable, so a technology is only ever claimed because a named file or a
named dependency was found. No guessing, no model.

Adding coverage means adding a row. See CONTRIBUTING.md.
"""

from __future__ import annotations

#: Directories never walked: vendored code, build output, virtualenvs, caches.
IGNORED_DIRS = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        ".idea",
        ".vscode",
        ".venv",
        "venv",
        "env",
        "envs",
        "virtualenv",
        "node_modules",
        "bower_components",
        "vendor",
        "third_party",
        "dist",
        "build",
        "out",
        "target",
        "bin",
        "obj",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        ".nox",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".terraform",
        ".gradle",
        ".dart_tool",
        "site-packages",
        "coverage",
        "htmlcov",
        ".repowise",
        ".ipynb_checkpoints",
        "Pods",
        "DerivedData",
        # Dependency and build caches. These hold third-party source that would
        # otherwise dominate language statistics -- a vendored llama.cpp under
        # .cache/ can make a Python service look like a C++ project.
        ".cache",
        ".ccache",
        ".cargo",
        ".npm",
        ".pnpm-store",
        ".yarn",
        ".bundle",
        ".conda",
        ".m2",
        ".mvn",
        ".stack-work",
        ".cxx",
        ".externalNativeBuild",
        "_deps",
        "cmake-build-debug",
        "cmake-build-release",
        "bazel-out",
        "cdk.out",
        ".serverless",
        ".vercel",
        ".output",
        ".angular",
        ".parcel-cache",
        "storybook-static",
    }
)

#: File extensions that are data/assets rather than source, skipped for
#: language statistics but still counted in totals.
BINARY_EXTENSIONS = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".svg", ".pdf",
        ".zip", ".gz", ".tgz", ".bz2", ".xz", ".7z", ".rar", ".jar", ".war",
        ".so", ".dylib", ".dll", ".exe", ".bin", ".o", ".a", ".class", ".pyc",
        ".mp3", ".mp4", ".wav", ".mov", ".avi", ".mkv", ".flac", ".ogg",
        ".ttf", ".otf", ".woff", ".woff2", ".eot",
        ".parquet", ".pkl", ".npy", ".npz", ".onnx", ".pt", ".pth", ".safetensors",
        ".h5", ".pb", ".tflite", ".db", ".sqlite", ".sqlite3", ".xlsx", ".docx",
    }
)

EXTENSION_LANGUAGES: dict[str, str] = {
    ".py": "Python",
    ".pyi": "Python",
    ".ipynb": "Jupyter Notebook",
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".jsx": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".java": "Java",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".scala": "Scala",
    ".go": "Go",
    ".rs": "Rust",
    ".rb": "Ruby",
    ".php": "PHP",
    ".cs": "C#",
    ".fs": "F#",
    ".c": "C",
    ".h": "C",
    ".cc": "C++",
    ".cpp": "C++",
    ".cxx": "C++",
    ".hpp": "C++",
    ".hh": "C++",
    ".m": "Objective-C",
    ".mm": "Objective-C++",
    ".swift": "Swift",
    ".dart": "Dart",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".fish": "Shell",
    ".ps1": "PowerShell",
    ".bat": "Batch",
    ".sql": "SQL",
    ".r": "R",
    ".jl": "Julia",
    ".lua": "Lua",
    ".pl": "Perl",
    ".ex": "Elixir",
    ".exs": "Elixir",
    ".erl": "Erlang",
    ".hs": "Haskell",
    ".clj": "Clojure",
    ".vue": "Vue",
    ".svelte": "Svelte",
    ".html": "HTML",
    ".htm": "HTML",
    ".css": "CSS",
    ".scss": "SCSS",
    ".sass": "Sass",
    ".less": "Less",
    ".tf": "Terraform",
    ".hcl": "HCL",
    ".proto": "Protocol Buffers",
    ".graphql": "GraphQL",
    ".gql": "GraphQL",
    ".sol": "Solidity",
    ".zig": "Zig",
    ".nim": "Nim",
    ".v": "V",
    ".asm": "Assembly",
    ".cu": "CUDA",
    ".cuh": "CUDA",
}

#: Manifest filename -> (ecosystem, package manager label).
MANIFESTS: dict[str, tuple[str, str]] = {
    "requirements.txt": ("pypi", "pip"),
    "requirements-dev.txt": ("pypi", "pip"),
    "requirements-lock.txt": ("pypi", "pip"),
    "pyproject.toml": ("pypi", "pip"),
    "setup.py": ("pypi", "setuptools"),
    "setup.cfg": ("pypi", "setuptools"),
    "Pipfile": ("pypi", "pipenv"),
    "poetry.lock": ("pypi", "poetry"),
    "uv.lock": ("pypi", "uv"),
    "environment.yml": ("conda", "conda"),
    "environment.yaml": ("conda", "conda"),
    "package.json": ("npm", "npm"),
    "pnpm-lock.yaml": ("npm", "pnpm"),
    "yarn.lock": ("npm", "yarn"),
    "bun.lockb": ("npm", "bun"),
    "go.mod": ("go", "go modules"),
    "Cargo.toml": ("crates", "cargo"),
    "Gemfile": ("rubygems", "bundler"),
    "composer.json": ("packagist", "composer"),
    "pom.xml": ("maven", "maven"),
    "build.gradle": ("maven", "gradle"),
    "build.gradle.kts": ("maven", "gradle"),
    "build.sbt": ("maven", "sbt"),
    "Package.swift": ("swiftpm", "swift package manager"),
    "pubspec.yaml": ("pub", "pub"),
    "mix.exs": ("hex", "mix"),
    "Podfile": ("cocoapods", "cocoapods"),
    "deno.json": ("deno", "deno"),
}

#: Exact filename or suffix -> (category, canonical technology).
#: Suffix rules start with ``*``.
FILE_SIGNATURES: dict[str, tuple[str, str]] = {
    "dockerfile": ("infrastructure", "Docker"),
    "*.dockerfile": ("infrastructure", "Docker"),
    "docker-compose.yml": ("infrastructure", "Docker Compose"),
    "docker-compose.yaml": ("infrastructure", "Docker Compose"),
    "compose.yml": ("infrastructure", "Docker Compose"),
    "compose.yaml": ("infrastructure", "Docker Compose"),
    "makefile": ("infrastructure", "Make"),
    "justfile": ("infrastructure", "Just"),
    "taskfile.yml": ("infrastructure", "Task"),
    "procfile": ("infrastructure", "Procfile"),
    "vagrantfile": ("infrastructure", "Vagrant"),
    "skaffold.yaml": ("infrastructure", "Skaffold"),
    "chart.yaml": ("infrastructure", "Helm"),
    "kustomization.yaml": ("infrastructure", "Kustomize"),
    "*.tf": ("infrastructure", "Terraform"),
    "*.tfvars": ("infrastructure", "Terraform"),
    "pulumi.yaml": ("infrastructure", "Pulumi"),
    "serverless.yml": ("infrastructure", "Serverless Framework"),
    "ansible.cfg": ("infrastructure", "Ansible"),
    "playbook.yml": ("infrastructure", "Ansible"),
    "cloudbuild.yaml": ("ci", "Google Cloud Build"),
    "cloudbuild.yml": ("ci", "Google Cloud Build"),
    ".gitlab-ci.yml": ("ci", "GitLab CI"),
    "jenkinsfile": ("ci", "Jenkins"),
    "azure-pipelines.yml": ("ci", "Azure Pipelines"),
    ".travis.yml": ("ci", "Travis CI"),
    ".circleci/config.yml": ("ci", "CircleCI"),
    "app.yaml": ("cloud", "Google App Engine"),
    "vercel.json": ("cloud", "Vercel"),
    "netlify.toml": ("cloud", "Netlify"),
    "fly.toml": ("cloud", "Fly.io"),
    "railway.json": ("cloud", "Railway"),
    "render.yaml": ("cloud", "Render"),
    "template.yaml": ("cloud", "AWS SAM"),
    "samconfig.toml": ("cloud", "AWS SAM"),
    "firebase.json": ("cloud", "Firebase"),
    "*.tsx": ("frontend", "React"),
    "*.vue": ("frontend", "Vue"),
    "*.svelte": ("frontend", "Svelte"),
    "tailwind.config.js": ("frontend", "Tailwind CSS"),
    "tailwind.config.ts": ("frontend", "Tailwind CSS"),
    "next.config.js": ("frameworks", "Next.js"),
    "next.config.ts": ("frameworks", "Next.js"),
    "nuxt.config.ts": ("frameworks", "Nuxt"),
    "vite.config.ts": ("frontend", "Vite"),
    "vite.config.js": ("frontend", "Vite"),
    "webpack.config.js": ("frontend", "Webpack"),
    "manage.py": ("frameworks", "Django"),
    "pytest.ini": ("testing", "pytest"),
    "conftest.py": ("testing", "pytest"),
    "tox.ini": ("testing", "tox"),
    "jest.config.js": ("testing", "Jest"),
    "jest.config.ts": ("testing", "Jest"),
    "playwright.config.ts": ("testing", "Playwright"),
    "cypress.config.ts": ("testing", "Cypress"),
    "*.proto": ("protocols", "gRPC / Protocol Buffers"),
    "*.graphql": ("protocols", "GraphQL"),
    "openapi.yaml": ("protocols", "OpenAPI"),
    "openapi.json": ("protocols", "OpenAPI"),
    "swagger.yaml": ("protocols", "OpenAPI"),
    "asyncapi.yaml": ("protocols", "AsyncAPI"),
    ".mcp.json": ("protocols", "Model Context Protocol"),
    "mcp.json": ("protocols", "Model Context Protocol"),
    "redis.conf": ("datastores", "Redis"),
    "alembic.ini": ("datastores", "Alembic"),
    "schema.prisma": ("datastores", "Prisma"),
    "my.cnf": ("datastores", "MySQL"),
    "*.ipynb": ("ml_ai", "Jupyter"),
    "dvc.yaml": ("ml_ai", "DVC"),
    "params.yaml": ("ml_ai", "DVC"),
}

#: Directory name -> (category, technology). Checked against every walked dir.
DIR_SIGNATURES: dict[str, tuple[str, str]] = {
    ".github/workflows": ("ci", "GitHub Actions"),
    "k8s": ("infrastructure", "Kubernetes"),
    "kubernetes": ("infrastructure", "Kubernetes"),
    "helm": ("infrastructure", "Helm"),
    "terraform": ("infrastructure", "Terraform"),
    "migrations": ("datastores", "Schema migrations"),
    "notebooks": ("ml_ai", "Jupyter"),
}

#: Dependency name (lowercase, exact) -> (category, canonical technology).
#: Keys are matched against the normalised package name from any ecosystem.
DEPENDENCY_SIGNATURES: dict[str, tuple[str, str]] = {
    # --- Python web / API ------------------------------------------------
    "fastapi": ("frameworks", "FastAPI"),
    "flask": ("frameworks", "Flask"),
    "django": ("frameworks", "Django"),
    "djangorestframework": ("frameworks", "Django REST Framework"),
    "starlette": ("frameworks", "Starlette"),
    "uvicorn": ("frameworks", "Uvicorn"),
    "gunicorn": ("frameworks", "Gunicorn"),
    "hypercorn": ("frameworks", "Hypercorn"),
    "tornado": ("frameworks", "Tornado"),
    "aiohttp": ("frameworks", "aiohttp"),
    "sanic": ("frameworks", "Sanic"),
    "litestar": ("frameworks", "Litestar"),
    "streamlit": ("frameworks", "Streamlit"),
    "gradio": ("frameworks", "Gradio"),
    "chainlit": ("frameworks", "Chainlit"),
    "dash": ("frameworks", "Dash"),
    "typer": ("frameworks", "Typer"),
    "click": ("frameworks", "Click"),
    "celery": ("frameworks", "Celery"),
    "pydantic": ("frameworks", "Pydantic"),
    "sqlalchemy": ("datastores", "SQLAlchemy"),
    "alembic": ("datastores", "Alembic"),
    # --- Datastores ------------------------------------------------------
    "psycopg2": ("datastores", "PostgreSQL"),
    "psycopg2-binary": ("datastores", "PostgreSQL"),
    "psycopg": ("datastores", "PostgreSQL"),
    "asyncpg": ("datastores", "PostgreSQL"),
    "pg": ("datastores", "PostgreSQL"),
    "pymysql": ("datastores", "MySQL"),
    "mysqlclient": ("datastores", "MySQL"),
    "mysql2": ("datastores", "MySQL"),
    "redis": ("datastores", "Redis"),
    "ioredis": ("datastores", "Redis"),
    "pymongo": ("datastores", "MongoDB"),
    "motor": ("datastores", "MongoDB"),
    "mongoose": ("datastores", "MongoDB"),
    "elasticsearch": ("datastores", "Elasticsearch"),
    "opensearch-py": ("datastores", "OpenSearch"),
    "neo4j": ("datastores", "Neo4j"),
    "duckdb": ("datastores", "DuckDB"),
    "clickhouse-driver": ("datastores", "ClickHouse"),
    "cassandra-driver": ("datastores", "Cassandra"),
    "chromadb": ("datastores", "Chroma (vector DB)"),
    "qdrant-client": ("datastores", "Qdrant (vector DB)"),
    "pinecone-client": ("datastores", "Pinecone (vector DB)"),
    "pinecone": ("datastores", "Pinecone (vector DB)"),
    "weaviate-client": ("datastores", "Weaviate (vector DB)"),
    "faiss-cpu": ("datastores", "FAISS (vector index)"),
    "faiss-gpu": ("datastores", "FAISS (vector index)"),
    "lancedb": ("datastores", "LanceDB"),
    "pgvector": ("datastores", "pgvector"),
    "supabase": ("datastores", "Supabase"),
    "prisma": ("datastores", "Prisma"),
    "sqlite3": ("datastores", "SQLite"),
    "aiosqlite": ("datastores", "SQLite"),
    "boto3": ("cloud", "AWS SDK"),
    "botocore": ("cloud", "AWS SDK"),
    # --- Cloud -----------------------------------------------------------
    "google-cloud-storage": ("cloud", "Google Cloud Storage"),
    "google-cloud-aiplatform": ("cloud", "Google Vertex AI"),
    "google-cloud-firestore": ("cloud", "Google Firestore"),
    "google-cloud-bigquery": ("cloud", "Google BigQuery"),
    "google-cloud-pubsub": ("cloud", "Google Pub/Sub"),
    "google-cloud-run": ("cloud", "Google Cloud Run"),
    "google-auth": ("cloud", "Google Cloud"),
    "azure-identity": ("cloud", "Microsoft Azure"),
    "azure-storage-blob": ("cloud", "Azure Blob Storage"),
    "firebase-admin": ("cloud", "Firebase"),
    "modal": ("cloud", "Modal"),
    "runpod": ("cloud", "RunPod"),
    # --- AI / ML ---------------------------------------------------------
    "openai": ("ml_ai", "OpenAI API"),
    "anthropic": ("ml_ai", "Anthropic API"),
    "google-generativeai": ("ml_ai", "Google Gemini API"),
    "google-genai": ("ml_ai", "Google Gemini API"),
    "mistralai": ("ml_ai", "Mistral API"),
    "cohere": ("ml_ai", "Cohere API"),
    "groq": ("ml_ai", "Groq API"),
    "ollama": ("ml_ai", "Ollama"),
    "litellm": ("ml_ai", "LiteLLM"),
    "vllm": ("ml_ai", "vLLM"),
    "langchain": ("ml_ai", "LangChain"),
    "langchain-core": ("ml_ai", "LangChain"),
    "langchain-community": ("ml_ai", "LangChain"),
    "langgraph": ("ml_ai", "LangGraph"),
    "llama-index": ("ml_ai", "LlamaIndex"),
    "llama_index": ("ml_ai", "LlamaIndex"),
    "haystack-ai": ("ml_ai", "Haystack"),
    "dspy": ("ml_ai", "DSPy"),
    "dspy-ai": ("ml_ai", "DSPy"),
    "crewai": ("ml_ai", "CrewAI"),
    "autogen": ("ml_ai", "AutoGen"),
    "pyautogen": ("ml_ai", "AutoGen"),
    "google-adk": ("ml_ai", "Google Agent Development Kit"),
    "smolagents": ("ml_ai", "smolagents"),
    "mcp": ("protocols", "Model Context Protocol"),
    "fastmcp": ("protocols", "Model Context Protocol"),
    "instructor": ("ml_ai", "Instructor"),
    "guardrails-ai": ("ml_ai", "Guardrails"),
    "transformers": ("ml_ai", "Hugging Face Transformers"),
    "diffusers": ("ml_ai", "Hugging Face Diffusers"),
    "accelerate": ("ml_ai", "Hugging Face Accelerate"),
    "peft": ("ml_ai", "PEFT"),
    "trl": ("ml_ai", "TRL"),
    "datasets": ("ml_ai", "Hugging Face Datasets"),
    "sentence-transformers": ("ml_ai", "Sentence Transformers"),
    "torch": ("ml_ai", "PyTorch"),
    "torchvision": ("ml_ai", "PyTorch"),
    "torchaudio": ("ml_ai", "PyTorch"),
    "pytorch-lightning": ("ml_ai", "PyTorch Lightning"),
    "lightning": ("ml_ai", "PyTorch Lightning"),
    "tensorflow": ("ml_ai", "TensorFlow"),
    "keras": ("ml_ai", "Keras"),
    "jax": ("ml_ai", "JAX"),
    "flax": ("ml_ai", "Flax"),
    "scikit-learn": ("ml_ai", "scikit-learn"),
    "sklearn": ("ml_ai", "scikit-learn"),
    "xgboost": ("ml_ai", "XGBoost"),
    "lightgbm": ("ml_ai", "LightGBM"),
    "catboost": ("ml_ai", "CatBoost"),
    "statsmodels": ("ml_ai", "statsmodels"),
    "hmmlearn": ("ml_ai", "hmmlearn (HMM)"),
    "pomegranate": ("ml_ai", "pomegranate (probabilistic models)"),
    "filterpy": ("ml_ai", "FilterPy (state estimation)"),
    "opencv-python": ("ml_ai", "OpenCV"),
    "opencv-python-headless": ("ml_ai", "OpenCV"),
    "opencv-contrib-python": ("ml_ai", "OpenCV"),
    "mediapipe": ("ml_ai", "MediaPipe"),
    "ultralytics": ("ml_ai", "Ultralytics YOLO"),
    "pillow": ("ml_ai", "Pillow (imaging)"),
    "scikit-image": ("ml_ai", "scikit-image"),
    "albumentations": ("ml_ai", "Albumentations"),
    "easyocr": ("ml_ai", "EasyOCR"),
    "pytesseract": ("ml_ai", "Tesseract OCR"),
    "paddleocr": ("ml_ai", "PaddleOCR"),
    "whisper": ("ml_ai", "OpenAI Whisper"),
    "openai-whisper": ("ml_ai", "OpenAI Whisper"),
    "faster-whisper": ("ml_ai", "faster-whisper"),
    "speechrecognition": ("ml_ai", "SpeechRecognition"),
    "pyaudio": ("ml_ai", "PyAudio"),
    "sounddevice": ("ml_ai", "sounddevice"),
    "librosa": ("ml_ai", "librosa (audio)"),
    "pydub": ("ml_ai", "pydub (audio)"),
    "torchvision.io": ("ml_ai", "PyTorch"),
    "moviepy": ("ml_ai", "MoviePy (video)"),
    "ffmpeg-python": ("ml_ai", "FFmpeg"),
    "imageio": ("ml_ai", "imageio"),
    "elevenlabs": ("ml_ai", "ElevenLabs TTS"),
    "deepgram-sdk": ("ml_ai", "Deepgram ASR"),
    "gtts": ("ml_ai", "gTTS"),
    "pyttsx3": ("ml_ai", "pyttsx3 TTS"),
    "numpy": ("ml_ai", "NumPy"),
    "pandas": ("ml_ai", "pandas"),
    "scipy": ("ml_ai", "SciPy"),
    "polars": ("ml_ai", "Polars"),
    "matplotlib": ("ml_ai", "Matplotlib"),
    "plotly": ("ml_ai", "Plotly"),
    "seaborn": ("ml_ai", "seaborn"),
    "networkx": ("ml_ai", "NetworkX"),
    "gymnasium": ("ml_ai", "Gymnasium (RL)"),
    "gym": ("ml_ai", "Gym (RL)"),
    "stable-baselines3": ("ml_ai", "Stable-Baselines3 (RL)"),
    "ray": ("ml_ai", "Ray"),
    "mlflow": ("ml_ai", "MLflow"),
    "wandb": ("ml_ai", "Weights & Biases"),
    "optuna": ("ml_ai", "Optuna"),
    "tiktoken": ("ml_ai", "tiktoken"),
    "onnxruntime": ("ml_ai", "ONNX Runtime"),
    "tritonclient": ("ml_ai", "NVIDIA Triton"),
    "pybullet": ("ml_ai", "PyBullet (simulation)"),
    "mujoco": ("ml_ai", "MuJoCo (simulation)"),
    "open3d": ("ml_ai", "Open3D"),
    "trimesh": ("ml_ai", "trimesh"),
    # --- Messaging / protocols -------------------------------------------
    "grpcio": ("protocols", "gRPC"),
    "grpcio-tools": ("protocols", "gRPC"),
    "protobuf": ("protocols", "Protocol Buffers"),
    "websockets": ("protocols", "WebSockets"),
    "socket.io": ("protocols", "Socket.IO"),
    "python-socketio": ("protocols", "Socket.IO"),
    "paho-mqtt": ("protocols", "MQTT"),
    "kafka-python": ("protocols", "Apache Kafka"),
    "confluent-kafka": ("protocols", "Apache Kafka"),
    "pika": ("protocols", "RabbitMQ"),
    "aio-pika": ("protocols", "RabbitMQ"),
    "nats-py": ("protocols", "NATS"),
    "graphene": ("protocols", "GraphQL"),
    "strawberry-graphql": ("protocols", "GraphQL"),
    "httpx": ("frameworks", "httpx"),
    "requests": ("frameworks", "requests"),
    "aiortc": ("protocols", "WebRTC"),
    "livekit": ("protocols", "LiveKit"),
    # --- JS / frontend ---------------------------------------------------
    "react": ("frontend", "React"),
    "react-dom": ("frontend", "React"),
    "next": ("frameworks", "Next.js"),
    "vue": ("frontend", "Vue"),
    "nuxt": ("frameworks", "Nuxt"),
    "svelte": ("frontend", "Svelte"),
    "@angular/core": ("frontend", "Angular"),
    "express": ("frameworks", "Express"),
    "fastify": ("frameworks", "Fastify"),
    "nestjs": ("frameworks", "NestJS"),
    "@nestjs/core": ("frameworks", "NestJS"),
    "tailwindcss": ("frontend", "Tailwind CSS"),
    "vite": ("frontend", "Vite"),
    "webpack": ("frontend", "Webpack"),
    "electron": ("frameworks", "Electron"),
    "react-native": ("frameworks", "React Native"),
    "expo": ("frameworks", "Expo"),
    "d3": ("frontend", "D3"),
    "three": ("frontend", "Three.js"),
    "@ai-sdk/react": ("ml_ai", "Vercel AI SDK"),
    "ai": ("ml_ai", "Vercel AI SDK"),
    "@modelcontextprotocol/sdk": ("protocols", "Model Context Protocol"),
    # --- Testing ---------------------------------------------------------
    "pytest": ("testing", "pytest"),
    "pytest-cov": ("testing", "pytest"),
    "pytest-asyncio": ("testing", "pytest"),
    "unittest2": ("testing", "unittest"),
    "hypothesis": ("testing", "Hypothesis"),
    "jest": ("testing", "Jest"),
    "vitest": ("testing", "Vitest"),
    "mocha": ("testing", "Mocha"),
    "playwright": ("testing", "Playwright"),
    "cypress": ("testing", "Cypress"),
    "selenium": ("testing", "Selenium"),
    "locust": ("testing", "Locust"),
    # --- Observability / infra clients ------------------------------------
    "prometheus-client": ("infrastructure", "Prometheus"),
    "opentelemetry-sdk": ("infrastructure", "OpenTelemetry"),
    "opentelemetry-api": ("infrastructure", "OpenTelemetry"),
    "sentry-sdk": ("infrastructure", "Sentry"),
    "structlog": ("infrastructure", "structlog"),
    "loguru": ("infrastructure", "loguru"),
    "docker": ("infrastructure", "Docker"),
    "kubernetes": ("infrastructure", "Kubernetes"),
    "temporalio": ("infrastructure", "Temporal"),
    "apache-airflow": ("infrastructure", "Apache Airflow"),
    "prefect": ("infrastructure", "Prefect"),
    "dagster": ("infrastructure", "Dagster"),
}

#: Relative weight of each category when scoring overlap. A shared framework or
#: datastore says far more about substantive similarity than a shared language.
CATEGORY_WEIGHTS: dict[str, float] = {
    "languages": 0.6,
    "frameworks": 1.4,
    "datastores": 1.3,
    "ml_ai": 1.5,
    "protocols": 1.2,
    "infrastructure": 0.9,
    "cloud": 0.9,
    "frontend": 1.0,
    "testing": 0.4,
    "package_managers": 0.3,
    "ci": 0.3,
}

#: Technologies so common they say nothing about substantive relatedness.
#: Kept in the inventory, discounted in scoring.
UBIQUITOUS = frozenset(
    {
        "ml_ai/numpy",
        "ml_ai/pandas",
        "ml_ai/matplotlib",
        "ml_ai/scipy",
        "frameworks/requests",
        "frameworks/httpx",
        "frameworks/pydantic",
        "frameworks/click",
        "package_managers/pip",
        "package_managers/npm",
        "testing/pytest",
        "ci/github actions",
        "infrastructure/make",
        "languages/shell",
        "languages/html",
        "languages/css",
        "languages/markdown",
        "languages/json",
        "languages/yaml",
    }
)

SPDX_HINTS: dict[str, str] = {
    "apache license": "Apache-2.0",
    "mit license": "MIT",
    "permission is hereby granted, free of charge": "MIT",
    "gnu affero general public license": "AGPL-3.0",
    "gnu general public license": "GPL-3.0",
    "gnu lesser general public license": "LGPL-3.0",
    "mozilla public license": "MPL-2.0",
    "bsd 3-clause": "BSD-3-Clause",
    "redistribution and use in source and binary forms": "BSD-3-Clause",
    "the unlicense": "Unlicense",
    "creative commons": "CC-BY-4.0",
    "business source license": "BUSL-1.1",
    "elastic license": "Elastic-2.0",
    "all rights reserved": "PROPRIETARY",
}
