"""The operative clause skeleton.

This is the deterministic half of the document. The text here is fixed,
reviewable once, and identical on every run -- which is the point: a generator
that produces different operative language each time cannot be reviewed by
counsel and then trusted.

Placeholders are ``str.format`` fields filled from the analysis and the
configuration:

``{company}``, ``{signatory}``, ``{company_business}``, ``{governing_law}``,
``{effective_date}``, ``{prior_invention_count}``.

Sections carry an optional ``drafting_note``: guidance for the reviewer that is
rendered as a note and is *not* part of the operative text. Sections marked
``jurisdiction_sensitive`` are the ones whose enforceability varies most by
jurisdiction; the renderer flags them.
"""

from __future__ import annotations

from typing import Any

#: The one-paragraph disclaimer that appears on every generated artifact.
DISCLAIMER = (
    "This document was generated by piia-cli from an automated analysis of source "
    "code repositories. It is a drafting aid, not legal advice, and no "
    "attorney-client relationship arises from its use. It must be reviewed and "
    "adapted by qualified counsel admitted in the relevant jurisdiction before it "
    "is executed. Statements about the scope, ownership or novelty of any work are "
    "derived from repository metadata and from a language model, and may be "
    "incomplete or wrong."
)

RECITALS: list[str] = [
    "The Company is engaged in the business described in Section 1.2 of this Agreement.",
    "{signatory} is or will be engaged by the Company as an employee, officer, founder, "
    "contractor or consultant (the \"Engagement\"), and in the course of the Engagement "
    "will have access to the Company's Confidential Information and will or may create "
    "Inventions.",
    "{signatory} has, prior to and independently of the Engagement, conceived, developed "
    "or reduced to practice certain works, which the parties intend to exclude from the "
    "assignment made under this Agreement, and which are listed in Exhibit A "
    "(\"Prior Inventions\").",
    "The parties enter into this Agreement to record the Company's rights in Inventions "
    "created in the course of the Engagement and to define, with specificity, the "
    "boundary between those Inventions and {signatory}'s Prior Inventions.",
]

SECTIONS: list[dict[str, Any]] = [
    {
        "id": "definitions",
        "heading": "Definitions",
        "clauses": [
            (
                "\"Agreement\" means this Proprietary Information and Inventions Agreement, "
                "including every Exhibit to it."
            ),
            (
                "\"Company Business\" means the following, together with its natural "
                "extensions, improvements and successors: {company_business}"
            ),
            (
                "\"Confidential Information\" means all non-public information of the Company, "
                "in any form, whether or not marked as confidential, including source code, "
                "object code, architecture, models, model weights, prompts, training data, "
                "datasets, algorithms, technical designs, product plans, pricing, customer and "
                "supplier information, financial information, personnel information, and any "
                "information of a third party that the Company is obliged to keep confidential. "
                "Confidential Information does not include information that: (a) is or becomes "
                "public through no act or omission of {signatory}; (b) was rightfully known to "
                "{signatory} before disclosure by the Company, as evidenced by contemporaneous "
                "written records; (c) is rightfully received from a third party without a duty "
                "of confidence; or (d) is independently developed without use of or reference "
                "to the Company's Confidential Information."
            ),
            (
                "\"Invention\" means any invention, discovery, improvement, development, "
                "design, work of authorship, software, source code, model, model weights, "
                "dataset, prompt, technique, method, process, formula, know-how, trade secret, "
                "mask work, trademark or other subject matter of intellectual property, whether "
                "or not patentable or registrable, and whether or not reduced to practice or "
                "fixed in a tangible medium."
            ),
            (
                "\"Company Invention\" means any Invention that {signatory} conceives, creates, "
                "develops, reduces to practice or acquires, alone or with others, during the "
                "Engagement, and that: (a) relates to the Company Business or to the Company's "
                "actual or demonstrably anticipated research or development; (b) results from "
                "work performed by {signatory} for the Company; or (c) is created using the "
                "Company's Confidential Information, equipment, supplies, facilities or "
                "personnel. Company Inventions do not include Prior Inventions."
            ),
            (
                "\"Prior Invention\" means an Invention that {signatory} conceived, created, "
                "developed or reduced to practice before the Engagement, or wholly outside the "
                "Engagement and without use of the Company's Confidential Information, "
                "equipment, supplies, facilities or personnel, and that is listed in Exhibit A. "
                "The parties acknowledge that Exhibit A identifies "
                "{prior_invention_count} such works."
            ),
            (
                "\"Third Party Information\" means confidential or proprietary information of a "
                "third party, including a former employer, a client, or an open-source project "
                "whose license imposes obligations on downstream use."
            ),
        ],
    },
    {
        "id": "confidentiality",
        "heading": "Confidential Information",
        "clauses": [
            (
                "{signatory} will hold all Confidential Information in strict confidence, will "
                "not disclose it to any person other than a Company employee or contractor who "
                "needs it for the Company Business and is bound by equivalent obligations, and "
                "will not use it for any purpose other than performing the Engagement."
            ),
            (
                "{signatory} will protect Confidential Information with at least the degree of "
                "care that {signatory} uses for their own most sensitive information, and in no "
                "event less than reasonable care. {signatory} will not store Confidential "
                "Information on personal accounts, personal devices or third-party services "
                "except as the Company permits in writing, and will not submit Confidential "
                "Information to any third-party artificial-intelligence service except as the "
                "Company permits in writing."
            ),
            (
                "If {signatory} is compelled by law or by an order of a court or regulator to "
                "disclose Confidential Information, {signatory} will, to the extent lawful, give "
                "the Company prompt written notice so that the Company may seek a protective "
                "order, and will disclose only what is legally required."
            ),
            (
                "These obligations survive the end of the Engagement and continue for so long "
                "as the information remains confidential. Obligations relating to trade secrets "
                "continue for so long as the information qualifies as a trade secret under "
                "applicable law."
            ),
            (
                "Nothing in this Agreement limits {signatory}'s right to report a possible "
                "violation of law to a government agency, to participate in an agency "
                "investigation, or to make any other legally protected disclosure, and no prior "
                "notice to the Company is required to do so."
            ),
        ],
    },
    {
        "id": "assignment",
        "heading": "Assignment of Company Inventions",
        "clauses": [
            (
                "{signatory} will promptly and fully disclose every Company Invention to the "
                "Company in writing."
            ),
            (
                "{signatory} hereby irrevocably assigns to the Company all right, title and "
                "interest worldwide in and to each Company Invention and all intellectual "
                "property rights in it. To the extent any Company Invention is a work made for "
                "hire under applicable copyright law, it is a work made for hire and the Company "
                "is its author; to the extent it is not, this Section operates as a present "
                "assignment."
            ),
            (
                "To the extent moral rights, rights of attribution and rights of integrity in a "
                "Company Invention cannot be assigned, {signatory} waives and agrees never to "
                "assert them against the Company, its successors, its licensees or its "
                "customers, to the fullest extent permitted by applicable law."
            ),
            (
                "{signatory} will keep and maintain adequate, current, written records of every "
                "Company Invention, in a form the Company specifies. Those records are the "
                "Company's property and will be surrendered to the Company at the end of the "
                "Engagement or on request."
            ),
        ],
    },
    {
        "id": "prior-inventions",
        "heading": "Prior Inventions and Excluded Works",
        "clauses": [
            (
                "Exhibit A lists every Prior Invention that {signatory} wishes to exclude from "
                "the assignment made by Section 3. {signatory} represents that Exhibit A is a "
                "complete and accurate list of such works as at the Effective Date, and that no "
                "Prior Invention has been omitted. If Exhibit A is left blank or states \"none\", "
                "{signatory} represents that there are no Prior Inventions."
            ),
            (
                "Nothing in this Agreement assigns any Prior Invention to the Company. Each "
                "Prior Invention remains the property of {signatory} or of its stated owner, "
                "subject only to the licence granted in Section 4.3."
            ),
            (
                "If {signatory} incorporates, or authorises the incorporation of, any Prior "
                "Invention into a Company product, process, service, model or machine, "
                "{signatory} grants the Company a non-exclusive, royalty-free, irrevocable, "
                "perpetual, worldwide licence, with the right to sublicense through multiple "
                "tiers, to make, have made, modify, use, reproduce, distribute, publicly "
                "perform, publicly display, create derivative works of and sell that Prior "
                "Invention, but only as part of or in connection with that product, process, "
                "service, model or machine."
            ),
            (
                "{signatory} will not incorporate any Prior Invention into a Company product, "
                "process, service, model or machine without first notifying the Company in "
                "writing, identifying the Prior Invention and the licence terms that apply to "
                "it, so that the Company may decide whether to accept those terms."
            ),
            (
                "{signatory} represents that, to their knowledge, no Prior Invention listed in "
                "Exhibit A is subject to any obligation to a third party that would prevent "
                "{signatory} from granting the licence in Section 4.3, and will promptly notify "
                "the Company on becoming aware of any such obligation."
            ),
        ],
    },
    {
        "id": "third-party",
        "heading": "Third Party and Open Source Information",
        "clauses": [
            (
                "{signatory} will not use or disclose Third Party Information in the course of "
                "the Engagement, and will not bring onto Company premises or into Company "
                "systems any document, code, model, dataset or other property belonging to a "
                "former employer or other third party, unless that party has consented in "
                "writing."
            ),
            (
                "{signatory} will comply with the Company's policy on open-source software. "
                "Before incorporating third-party or open-source material into a Company "
                "product, {signatory} will identify the material and its licence to the Company "
                "so that the Company may assess the resulting obligations, including any "
                "obligation to make source code available."
            ),
            (
                "{signatory} will identify to the Company any open-source or copyleft licence "
                "applying to a Prior Invention listed in Exhibit A, and acknowledges that such "
                "a licence may constrain the Company's use of any incorporated portion "
                "notwithstanding the licence granted in Section 4.3."
            ),
        ],
    },
    {
        "id": "no-conflict",
        "heading": "No Conflicting Obligations",
        "clauses": [
            (
                "{signatory} represents that performing this Agreement and the Engagement does "
                "not and will not breach any agreement with, or duty owed to, any third party, "
                "including any agreement to keep information confidential or to assign "
                "inventions."
            ),
            (
                "{signatory} has not entered into, and will not enter into, any agreement that "
                "conflicts with this Agreement. {signatory} has disclosed to the Company every "
                "existing obligation that could reasonably be expected to affect the Company's "
                "rights in Company Inventions."
            ),
        ],
    },
    {
        "id": "further-assurances",
        "heading": "Further Assurances",
        "clauses": [
            (
                "{signatory} will, at the Company's request and expense, execute every document "
                "and take every action the Company reasonably requires to apply for, prosecute, "
                "obtain, maintain, enforce and defend intellectual property rights in Company "
                "Inventions, in any country, during and after the Engagement."
            ),
            (
                "If the Company is unable, after reasonable effort, to secure {signatory}'s "
                "signature for such a purpose, {signatory} irrevocably appoints the Company and "
                "its duly authorised officers as {signatory}'s agent and attorney-in-fact, "
                "coupled with an interest, to execute and file such documents and to do all "
                "other lawfully permitted acts for that purpose, with the same legal effect as "
                "if executed by {signatory}. This appointment is limited to the purposes stated "
                "in this Section."
            ),
        ],
    },
    {
        "id": "return-of-property",
        "heading": "Return of Company Property",
        "clauses": [
            (
                "At the end of the Engagement, or earlier on request, {signatory} will return to "
                "the Company all Company property and all material containing or derived from "
                "Confidential Information, in every copy and every medium, and will "
                "irretrievably delete Confidential Information from any personal device, account "
                "or service, certifying that deletion in writing if the Company asks."
            ),
            (
                "{signatory} may retain a copy of any Prior Invention listed in Exhibit A, "
                "provided that the copy contains no Confidential Information and no Company "
                "Invention."
            ),
        ],
    },
    {
        "id": "restrictive-covenants",
        "heading": "Non-Solicitation",
        "jurisdiction_sensitive": True,
        "drafting_note": (
            "Restrictive covenants are void or narrowly limited in many jurisdictions "
            "(for example California Business and Professions Code section 16600, and the "
            "FTC's position on non-competes). Counsel should confirm the enforceability, "
            "scope and duration of this Section under {governing_law}, and delete it where "
            "it is unenforceable. No non-compete is included by default."
        ),
        "clauses": [
            (
                "For twelve (12) months after the end of the Engagement, {signatory} will not "
                "solicit any employee or contractor of the Company to leave the Company, to the "
                "extent such a restriction is enforceable under applicable law. This Section "
                "does not restrict general advertising not targeted at Company personnel, and "
                "does not restrict {signatory}'s right to work."
            ),
        ],
    },
    {
        "id": "general",
        "heading": "General Provisions",
        "clauses": [
            (
                "Governing law. This Agreement is governed by and construed in accordance with "
                "the laws of {governing_law}, without regard to its conflict of laws rules."
            ),
            (
                "Equitable relief. {signatory} acknowledges that a breach of Sections 2, 3 or 4 "
                "may cause the Company irreparable harm for which damages alone would be an "
                "inadequate remedy, and that the Company may seek injunctive or other equitable "
                "relief in addition to any other remedy, without the necessity of posting a bond "
                "except as required by law."
            ),
            (
                "Assignment. The Company may assign this Agreement, in whole or in part, to a "
                "successor in interest or an acquirer of the relevant business or assets. "
                "{signatory} may not assign this Agreement."
            ),
            (
                "Severability. If any provision of this Agreement is held unenforceable, it will "
                "be modified to the minimum extent necessary to make it enforceable, or severed "
                "if it cannot be, and the remaining provisions continue in full force."
            ),
            (
                "Entire agreement. This Agreement, including its Exhibits, is the entire "
                "agreement between the parties on its subject matter and supersedes all prior "
                "discussions and agreements on that subject matter. Where this Agreement "
                "conflicts with an earlier agreement between the parties on invention "
                "assignment or confidentiality, this Agreement prevails as to that subject "
                "matter."
            ),
            (
                "Amendment and waiver. This Agreement may be amended only by a writing signed "
                "by both parties. A waiver is effective only if in writing and signed by the "
                "waiving party, and is not a waiver of any other or later breach."
            ),
            (
                "Survival. Sections 1, 2, 3, 4, 5, 7, 8 and 10 survive the end of the "
                "Engagement, however it ends."
            ),
            (
                "Counterparts. This Agreement may be executed in counterparts, including by "
                "electronic signature, each of which is an original and all of which together "
                "form one agreement."
            ),
            (
                "No employment guarantee. Nothing in this Agreement creates or implies any "
                "obligation to continue the Engagement for any period, or alters the at-will "
                "nature of any employment relationship where that applies."
            ),
        ],
    },
]

#: Exhibit headings, in order. Exhibit A is the reason this tool exists.
EXHIBITS: list[dict[str, str]] = [
    {
        "id": "exhibit-a",
        "label": "Exhibit A",
        "heading": "Prior Inventions Excluded from Assignment",
        "preamble": (
            "The following works were conceived, created, developed or reduced to practice by "
            "{signatory} before or independently of the Engagement, and are excluded from the "
            "assignment made by Section 3 of the Agreement. Each entry states the repository "
            "from which it was identified, the commit at which it was analysed, its technologies, "
            "and the boundary against Company work."
        ),
    },
    {
        "id": "exhibit-b",
        "label": "Exhibit B",
        "heading": "Deterministic Analysis Evidence",
        "preamble": (
            "This Exhibit records the deterministic analysis from which Exhibit A was prepared, "
            "so that it can be reproduced and audited. Each repository is identified by the "
            "commit analysed. The analysis digest below covers every fact in this Exhibit; "
            "re-running the analysis at the same commits reproduces the same digest."
        ),
    },
    {
        "id": "exhibit-c",
        "label": "Exhibit C",
        "heading": "Review Checklist for Counsel",
        "preamble": (
            "The following matters were flagged during analysis and should be resolved before "
            "this Agreement is executed. Items marked \"deterministic\" arise from a rule applied "
            "to repository evidence; items marked \"model\" were raised by a language model and "
            "must be independently verified."
        ),
    },
]
