"""DOCX rendering.

Counsel redline in Word, so the DOCX is a first-class output rather than a
Markdown export. It is built structurally from the document object -- real
Word headings, real tables, real signature blocks -- so styles and the
navigation pane work and a reviewer can turn on track changes and start editing.

Requires the ``docx`` extra: ``pip install piia-cli[docx]``.
"""

from __future__ import annotations

import io
from typing import Any

from piia.documents.assemble import PiiaDocument
from piia.errors import DependencyMissingError, DocumentError

DISCLAIMER_LABEL = "Not legal advice."


def render_docx(doc: PiiaDocument) -> bytes:
    try:
        from docx import Document  # type: ignore[import-not-found]
        from docx.enum.text import WD_ALIGN_PARAGRAPH  # type: ignore[import-not-found]
        from docx.shared import Pt  # type: ignore[import-not-found]
    except ImportError as exc:
        raise DependencyMissingError("python-docx", "docx", "render DOCX output") from exc

    payload = doc.to_dict()
    try:
        document = Document()
        core = document.core_properties
        core.title = payload["title"]
        core.author = "piia-cli"
        core.comments = (
            f"Generated by piia-cli {payload['provenance'].get('tool_version')}; "
            f"analysis digest {payload['evidence']['analysis_digest']}. Not legal advice."
        )

        document.add_heading(payload["title"], level=0)

        notice = document.add_paragraph()
        run = notice.add_run(f"{DISCLAIMER_LABEL} ")
        run.bold = True
        notice.add_run(payload["disclaimer"])
        notice.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

        _kv_table(
            document,
            [
                ("Company", payload["company"]["name"]),
                ("Signatory", payload["signatory"]["full_name"]),
                ("Title", payload["signatory"].get("title") or "-"),
                ("Effective date", payload["effective_date"]),
                ("Governing law", payload["governing_law"]),
                ("Prior Inventions disclosed", str(len(payload["prior_inventions"]))),
                ("Analysis digest", payload["evidence"]["analysis_digest"]),
                ("Generated", f"{payload['generated_at']} by piia-cli"),
            ],
        )

        document.add_heading("Executive Summary", level=1)
        document.add_paragraph(payload["executive_summary"])

        document.add_heading("Agreement", level=1)
        document.add_paragraph(
            f"This Proprietary Information and Inventions Agreement (the “Agreement”) is "
            f"made as of {payload['effective_date']} (the “Effective Date”) between "
            f"{payload['company']['name']} (the “Company”) and "
            f"{payload['signatory']['full_name']} (the “Signatory”)."
        )

        document.add_heading("Recitals", level=2)
        for recital in payload["recitals"]:
            document.add_paragraph(recital, style="List Number")
        document.add_paragraph("The parties agree as follows.")

        for section in payload["sections"]:
            document.add_heading(f"{section['number']}. {section['heading']}", level=2)
            if section.get("drafting_note"):
                note = document.add_paragraph()
                label = note.add_run("Drafting note. ")
                label.bold = True
                label.italic = True
                note.add_run(section["drafting_note"]).italic = True
            for clause in section["clauses"]:
                para = document.add_paragraph()
                para.add_run(f"{clause['number']}  ").bold = True
                para.add_run(clause["text"])
                para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

        document.add_heading("Signatures", level=2)
        document.add_paragraph("Executed as of the Effective Date.")
        signatures = document.add_table(rows=5, cols=2)
        signatures.style = "Table Grid"
        signatures.cell(0, 0).text = payload["company"]["name"]
        signatures.cell(0, 1).text = payload["signatory"]["full_name"]
        for row, label in enumerate(("Signature", "Name", "Title", "Date"), start=1):
            signatures.cell(row, 0).text = f"{label}: "
            signatures.cell(row, 1).text = f"{label}: "
        signatures.cell(2, 1).text = f"Name: {payload['signatory']['full_name']}"

        # -- Exhibit A ------------------------------------------------------
        document.add_page_break()
        exhibit_a = _exhibit(payload, "exhibit-a")
        document.add_heading(f"{exhibit_a['label']} — {exhibit_a['heading']}", level=1)
        document.add_paragraph(exhibit_a["preamble"])

        if not payload["prior_inventions"]:
            document.add_paragraph("None. The Signatory has declared no Prior Inventions.")
        else:
            summary = document.add_table(rows=1, cols=5)
            summary.style = "Light Grid Accent 1"
            for index, header in enumerate(
                ("#", "Work", "Repository", "Relatedness", "License")
            ):
                cell = summary.rows[0].cells[index]
                cell.text = header
                for paragraph in cell.paragraphs:
                    for cell_run in paragraph.runs:
                        cell_run.bold = True
            for index, pi in enumerate(payload["prior_inventions"], start=1):
                cells = summary.add_row().cells
                cells[0].text = f"A.{index}"
                cells[1].text = str(pi.get("title", ""))
                cells[2].text = str(pi.get("repository", ""))
                cells[3].text = (
                    f"{pi.get('relatedness', 'unknown')} "
                    f"({float(pi.get('overlap_score') or 0):.2f})"
                )
                cells[4].text = str(pi.get("license") or "not declared")

            for index, pi in enumerate(payload["prior_inventions"], start=1):
                document.add_heading(f"A.{index} {pi.get('title', '')}", level=2)
                _kv_table(
                    document,
                    [
                        ("Repository", str(pi.get("url") or pi.get("repository", ""))),
                        ("Commit analysed", str(pi.get("commit") or "not available")),
                        ("Created", str(pi.get("first_commit_date") or "not established")),
                        ("Last updated", str(pi.get("last_commit_date") or "not established")),
                        ("Declared license", str(pi.get("license") or "none detected")),
                        ("Asserted owner", str(pi.get("ownership", ""))),
                        (
                            "Measured relatedness",
                            f"{pi.get('relatedness', 'unknown')} "
                            f"(score {float(pi.get('overlap_score') or 0):.2f})",
                        ),
                        ("Incorporation risk", str(pi.get("incorporation_risk", "unknown"))),
                        (
                            "Drafted by",
                            "language model over deterministic evidence"
                            if pi.get("source") == "model"
                            else "deterministic template",
                        ),
                    ],
                )
                for label, key in (
                    ("Description", "description"),
                    ("Relationship to the Company Business", "relation_to_company_business"),
                    ("Reservation of rights", "carve_out_language"),
                ):
                    document.add_heading(label, level=3)
                    document.add_paragraph(str(pi.get(key, "")))
                document.add_heading("Technologies", level=3)
                document.add_paragraph(", ".join(pi.get("technologies") or []) or "none recorded")
                if pi.get("notes"):
                    para = document.add_paragraph()
                    para.add_run("To verify: ").bold = True
                    para.add_run(str(pi["notes"])).italic = True

        # -- Exhibit B ------------------------------------------------------
        document.add_page_break()
        exhibit_b = _exhibit(payload, "exhibit-b")
        document.add_heading(f"{exhibit_b['label']} — {exhibit_b['heading']}", level=1)
        document.add_paragraph(exhibit_b["preamble"])
        document.add_heading("B.1 Method", level=2)
        document.add_paragraph(payload["evidence"]["method"])
        document.add_heading("B.2 Repositories analysed", level=2)
        rows = [payload["evidence"]["target"], *payload["evidence"]["prior_works"]]
        _grid(
            document,
            ("Repository", "Role", "Commit", "First", "Last", "Commits", "License"),
            [
                (
                    str(row["repository"]),
                    "target" if index == 0 else "prior",
                    str(row.get("short_commit") or "-"),
                    str(row.get("first_commit_date") or "-"),
                    str(row.get("last_commit_date") or "-"),
                    str(row.get("commit_count", "-")),
                    str(row.get("license") or "-"),
                )
                for index, row in enumerate(rows)
            ],
        )
        document.add_heading("B.3 Measured relationship to the target work", level=2)
        _grid(
            document,
            ("Repository", "Overlap", "Dependency overlap", "Relatedness", "Predates target"),
            [
                (
                    str(cmp["repository"]),
                    f"{cmp['overlap_score']:.2f}",
                    f"{cmp['dependency_overlap']:.2f}",
                    str(cmp["relatedness"]),
                    "yes" if cmp["predates_target"] else ("no" if cmp["predates_target"] is False else "not verified"),
                )
                for cmp in payload["evidence"]["comparisons"]
            ],
        )

        # -- Exhibit C ------------------------------------------------------
        document.add_page_break()
        exhibit_c = _exhibit(payload, "exhibit-c")
        document.add_heading(f"{exhibit_c['label']} — {exhibit_c['heading']}", level=1)
        document.add_paragraph(exhibit_c["preamble"])
        if payload["review_checklist"]:
            _grid(
                document,
                ("Severity", "Item", "Why it matters", "Source"),
                [
                    (
                        str(item.get("severity", "")).upper(),
                        str(item.get("item", "")),
                        str(item.get("why", "")),
                        str(item.get("source", "deterministic")),
                    )
                    for item in payload["review_checklist"]
                ],
            )
        else:
            document.add_paragraph("No review items were raised.")
        if payload["open_source_notes"]:
            document.add_heading("C.1 Open-source and license notes", level=2)
            for note in payload["open_source_notes"]:
                document.add_paragraph(str(note), style="List Bullet")

        # -- Provenance -----------------------------------------------------
        document.add_heading("Provenance", level=1)
        provenance = payload["provenance"]
        _kv_table(
            document,
            [
                ("Tool", f"piia-cli {provenance.get('tool_version')}"),
                ("Generated at", str(provenance.get("generated_at"))),
                ("Analysis digest", str(provenance.get("analysis_digest"))),
                ("Model", str(provenance.get("model") or "none (deterministic draft)")),
                ("Endpoint", str(provenance.get("base_url") or "n/a")),
                ("Temperature", str(provenance.get("temperature"))),
                ("repowise used", "yes" if provenance.get("repowise_used") else "no"),
                (
                    "Model-drafted content",
                    ", ".join(provenance.get("model_generated_fields") or []) or "none",
                ),
            ],
        )
        if provenance.get("degraded"):
            document.add_heading("Degraded steps", level=2)
            for note in provenance["degraded"]:
                document.add_paragraph(str(note), style="List Bullet")

        footer = document.add_paragraph()
        footer_run = footer.add_run(
            "Generated by piia-cli (AGPL-3.0-or-later) — "
            "https://github.com/PIIA-CLI/PIIA-CLI"
        )
        footer_run.italic = True
        footer_run.font.size = Pt(8)

        buffer = io.BytesIO()
        document.save(buffer)
        return buffer.getvalue()
    except DependencyMissingError:
        raise
    except Exception as exc:
        raise DocumentError(
            f"DOCX rendering failed: {exc}",
            remediation="Render --format md or html instead, or report this as a bug.",
        ) from exc


def _exhibit(payload: dict[str, Any], exhibit_id: str) -> dict[str, Any]:
    for exhibit in payload["exhibits"]:
        if exhibit["id"] == exhibit_id:
            return exhibit
    return {"label": exhibit_id, "heading": "", "preamble": ""}


def _kv_table(document: Any, rows: list[tuple[str, str]]) -> None:
    table = document.add_table(rows=0, cols=2)
    table.style = "Light List Accent 1"
    for key, value in rows:
        cells = table.add_row().cells
        cells[0].text = key
        cells[1].text = value
        for paragraph in cells[0].paragraphs:
            for run in paragraph.runs:
                run.bold = True


def _grid(document: Any, headers: tuple[str, ...], rows: list[tuple[str, ...]]) -> None:
    table = document.add_table(rows=1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    for index, header in enumerate(headers):
        cell = table.rows[0].cells[index]
        cell.text = header
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True
    for row in rows:
        cells = table.add_row().cells
        for index, value in enumerate(row):
            cells[index].text = value
